export const filmList = [

    "Dirty Ho",
    "The Chinese Boxer",
    "Swordsman ",
    "Venom Mob in The Five Venoms",
    "Crippled Avengers",
    "Shaolin Temple",
    "Come Drink with Me ",
    "Killer Constable",
    "Seeding of a Ghost ",
    "In Our Mother’s House",
    "Blade Runner: The Final Cut",
    "Alien",
    "Gladiator",
    "Kingdom of Heaven",
    "Robin Hood",
    "Exodus: Gods and Kings",
    "Conquest of Paradise",
    "Black Hawk Down ",
    "A Good Year",
    "Thelma & Louise",
    "The Last Duel",
    "House of Gucci",
    "The Counsellor",
    "Dirty Harry",
    "Sudden Impact",
    "Cry Macho",
    "High Plains Drifter",
    "Pale Rider",
    "The Outlaw Josey Wales",
    "A Perfect World ",
    "Mystic River",
    "Bird",
    "Changeling(2008)",
    "Unforgiven",
    "J.Edgar",
    "Jersey Boys",
    "Flags of Our Fathers",
    "Letters from Iwo Jima",
    "American Sniper",
    "Sully",
    "The 15: 17 to Paris",
    "Richard Jewell",
    "White Hunter Black Heart",
    "The Bridges of Madison County",
    "The Walker ",
    "The Comfort of Strangers",
    "Cat People(1982)",
    "Dying of the Light(directors cut)",
    "Dominion: Prequel to The Exorcist(directors cut)",
    "The Life and Death of Colonel Blimp",
    "The Spy in Black",
    "Contraband",
    "The Battle of the River Plate",
    "Prisoners",
    "Sicario",
    "Enemy",
    "Polytechnique",
    "Tenebrae",
    "Night Train Murders ",
    "The Last House on the Left",
    "A Bay of Blood",
    "The Beyond",
    "The House by the Cemetery",
    "Zombie Flesh Eaters",
    "Possession(1981)",
    "Visiting Hours",
    "Gestapo’s Last Orgy",
    "The Witch Who Came from the Sea",
    "I Spit on Your Grave ",
    "The Shallows",
    "The Commuter",
    "Non - Stop",
    "Unknown",
    "Orphan",
    "Run All Night",
    "What Ever Happened to Baby Jane ?",
    "    Festen",
    "All about Love",
    "Dear Wendy ",
    "The Commune",
    "Another Round",
    "The Hunt",
    "Alien vs.Predator",
    "Three Musketeers(2011)",
    "Orphée",
    "Drive(2011)",
    "Pusher",
    "Bronson",
    "Valhalla Rising",
    "Only God Forgives",
    "The Neon Demon",
    "Lift to the Scaffold",
    "Murmur of the Heart",
    "Lacombe Lucien",
    "My Dinner with Andre",
    "Atlantic City",
    "The Fly",
    "Shivers",
    "The Brood",
    "Quebec in Rabid",
    "Scanners",
    "Dead Ringers",
    "Dead Zone",
    "NakeOrders to Kill d Lunch",
    "Cosmopolis",
    "J.G.Ballard in Crash",
    "Videodrome",
    "A History of Violence",
    "Peking Opera Blues",
    "Once upon a Time in China",
    "The Blade(1995)",
    "Dangerous Encounters – First Kind ",
    "Knock Off(1998)",
    "Time and Tide",
    "Fort Apache",
    "She Wore a Yellow Ribbon",
    "Rio Grande ",
    "Wagon Master",
    "The Searchers(1956)",
    "The Man Who Shot Liberty Valance",
    "The Texas Chain Saw Massacre",
    "Poltergeist",
    "The Funhouse",
    "Lifeforce(1985)",
    "Invaders from Mars ",
    "Toolbox Murders",
    "Dangerous Tonight",
    "The Mangler",
    "Mortuary",
    "Chainsaw Massacre 2",
    "The Talented Mr.Ripley ",
    "Plein Soleil",
    "The American Friend",
    "Cottage to Let",
    "Orders to Kill ",
    "A Pigeon Sat on a Branch Reflecting on Existence",
    "Second Floor",
    "You, the Living",
    "The Tingler",
    "House on Haunted Hill",
    "Strait - Jacket",
    "The Night Walker",
    "When Strangers Marry",
    "Stool Pigeon",
    "Hollywood Story",
    "Lone Star",
    "The Brother from Another Planet",
    "City of Hope",
    "Tokyo Sonata",
    "Cure",
    "Pulse",
    "Journey to the Shore",
    "Creepy(2016)",
    "To the Ends of the Earth",
    "Orlando(1992)",
    "Exotica",
    "Felicia’s Journey",
    "Devil’s Knot",
    "Where the Truth Lies",
    "The Watermelon Woman",
    "Quatermass and the Pit(1967)",
    "The Quatermass Xperiment",
    "Quatermass II",
    "The Abominable Snowman(1957)",
    "The Witches(1966)",
    "The Stone Tape",
    "The Woman in Black(1989)",
    "Funny Games(1997)",
    "Hidden(2005)",
    "White Ribbon",
    "The Piano Teacher",
    "Amour(2012)",
    "Happy End(2017)",
    "Seventh Continent",
    "Benny’s Video",
    "71 Fragments of a Chronology of Chance",
    "Funny Games(2007)",
    "Come Drink with Me",
    "Dragon Inn",
    "A Touch of Zen",
    "Raining in the Mountain",
    "Legend of the Mountain",
    "The Fate of Lee Khan",
    "The Valiant Ones",
    "Hardware(1990)",
    "Dust Devil",
    "Color Out of Space",
    "Lost Soul: The Doomed Journey of Richard Stanley’s Island of Dr.Moreau ",
    "Switchblade Romance",
    "The Hills Have Eyes(1977)",
    "The Hills Have Eyes(2007)",
    "Piranha(2010)",
    "Horns(2013)",
    "Paper Moon",
    "What’s Up, Doc ?",
    "    Targets(1968)",
    "The Other Side of the Wind",
    "Pulp Fiction",
    "Jackie Brown ",
    "Death Proof",
    "Inglourious Basterds",
    "Django Unchained",
    "Onibaba",
    "Kuroneko",
    "Live Today, Die Tomorrow!",
    "Black Panther",
    "Akira(1988)",
    "Ghost in the Shell(1995)",
    "Ghost in the Shell 2: Innocence(2004)",
    "Battle Angel Alita(1993)",
    "Appleseed(1988)",
    "Appleseed(2004)",
    "Paprika",
    "Paranormal Activity",
    "Sinister",
    "Get Out",
    "Jessabelle",
    "The Town That Dreaded Sundown(2014)",
    "Enter the Void",
    "Climax(2018)",
    "Unbreakable",
    "Split",
    "Glass",
    "The Village(2004)",
    "Signs",
    "The Visit",
    "Lady in the Water",
    "Tempo(2021)",
    "Kasaba",
    "Winter Sleep",
    "Requiem for a Vampire",
    "The Grapes of Death",
    "The Living Dead Girl",
    "Fascination(1979)",
    "The Iron Rose",
    "The Night of the Hunted ",
    "Two Orphan Vampires ",
    "The Fiancée of Dracula ",
    "Schoolgirl Hitchhikers ",
    "Zombie Lake",
    "Born of Fire",
    "Edward Scissorhands",
    "Sleepy Hollow(1999)",
    "Mars Attacks!",
    "Ed Wood",
    "Batman(1989)",
    "Batman Returns",
    "Miss Peregrine’s Home for Peculiar Children",
    "Do the Right Thing",
    "She's Gotta Have It (1986)",
    "Malcolm X(1992)",
    "Mo’ Better Blues",
    "Clockers",
    "Bamboozled",
    "25th Hour ",
    "Inside Man",
    "4 Little Girls",
    "Paris, Texas",
    "Wings of Desire",
    "The American Friend",
    "The Salt of the Earth ",
    "Good Morning, Night",
    "Vincere",
    "Slap the Monster on Page One ",
    "The Caretaker",
    "The Servant",
    "Betrayal",
    "Sleuth(2007)",
    "Cléo from 5 to 7",
    "Vagabond(1985)",
    "Barry Lyndon",
    "Dr.Strangelove",
    "Paths of Glory",
    "2001: A Space Odyssey",
    "Room 237(2012)",
    "Eyes Wide Shut",
    "An Actor's Revenge",
    "Alone across the Pacific",
    "The Burmese Harp",
    "Fires on the Plain(1959)",
    "Caravaggio(1986)",
    "Institute Benjamenta",
    "The Piano Tuner of Earthquakes",
    "The Bird with the Crystal Plumage",
    "Deep Red",
    "Blowup(1966)",
    "The Girl Who Knew Too Much",
    "The Mask of Satan",
    "Blood and Black Lace ",
    "What Have You Done to Solange ? (1972)",
    "Don’t Torture a Duckling",
    "The Short Night of the Glass Dolls ",
    "Your Vice Is a Locked Room and Only I Have the Key",
    "Badlands",
    "The Thin Red Line",
    "The Tree of Life",
    "Le Samouraï ",
    "Le Cercle rouge ",
    "Un flic",
    "The Army of Shadows",
    "Bob le flambeur",
    "Le Doulos",
    "Le Silence de la mer",
    "A Scanner Darkly",
    "Bernie(2011)",
    "The Newton Boys",
    "The School of Rock",
    "Bride of Frankenstein",
    "The Mummy(1932)",
    "The Old Dark House(1932)",
    "The Invisible Man(1933)",
    "Dracula’s Daughter(1936)",
    "Creature from the Black Lagoon(1954)",
    "Tarantula(1955)",
    "The Incredible Shrinking Man(1957)",
    "Werewolf of London(1935)",
    "Dr.Jekyll and Mr.Hyde",
    "Lost in Translation",
    "Marie Antoinette(2006)",
    "The Bling Ring",
    "Oldboy(2003)",
    "Stoker",
    "Sympathy for Mr.Vengeance",
    "Lady Vengeance",
    "Cat People(1942)",
    "The Curse of the Cat People",
    "I Walked with a Zombie",
    "The Leopard Man ",
    "The Body Snatcher(1945)",
    "Isle of the Dead",
    "Bedlam",
    "Apache Drums(1951)",
    "The Seventh Victim ",
    "The Ghost Ship(1943)",
    "Chinese Roulette",
    "Despair(1978)",
    "Touchez pas au grisbi",
    "Le Trou(1960)",
    "The Adventures of Arsène Lupin(1957)",
    "Goupi mains rouge(1943)",
    "The Face of Another ",
    "Death by Hanging",
    "Violent Cop(1989)",
    "Zatoichi(2003)",
    "Sonatine",
    "Hana - bi",
    "Kids Return",
    "Brother(2000)",
    "Out of Sight ",
    "The Limey",
    "Ocean’s Eleven",
    "Ocean’s Twelve",
    "Ocean’s Thirteen",
    "Schizopolis",
    "Solaris(2002)",
    "Che(2008)",
    "The Good German",
    "Traffic(2000)",
    "Erin Brockovich",
    "King of the Hill",
    "Bubble(2005)",
    "The Girlfriend Experience",
    "Magic Mike",
    "Kafka(1991)",
    "Faust(1926)",
    "Nosferatu",
    "Sunrise: A Song of Two Humans(1927)",
    "GoodFellas",
    "Casino(1995)",
    "Taxi Driver",
    "Raging Bull",
    "New York, New York(1977)",
    "The Last Temptation of Christ",
    "Kundun(1997)",
    "Gangs of New York",
    "The Aviator",
    "Wolf of Wall Street",
    "The Departed",
    "Who’s That Knocking at My Door",
    "Boxcar Bertha",
    "The Long Goodbye(1973)",
    "Nashville(1975)",
    "Gosford Park",
    "The Player(1992)",
    "Secret Honor",
    "Popeye(1980)",
    "A Prairie Home Companion",
    "McCabe & Mrs.Miller",
    "Buffalo Bill and the Indians",
    "Thieves like Us(1974)",
    "A Man Escaped",
    "Pickpocket(1959)",
    "The Trial of Joan of Arc(1962)",
    "Au hasard Balthazar",
    "Diary of a Country Priest",
    "Lancelot du Lac",
    "L’Argent(1983)",
    "The Masque of the Red Death",
    "Fahrenheit 451(1968)",
    "Walkabout(1971)",
    "The Man Who Fell to Earth",
    "Bad Timing",
    "The Witches(1990)",
    "Women on the Verge of a Nervous Breakdown",
    "Talk to Her",
    "Bad Education",
    "Tie Me Up! Tie Me Down! ",
    "Law of Desire",
    "Live Flesh",
    "Volver",
    "The Skin I Live In",
    "Blood and Black Lace",
    "Planet of the Vampires ",
    "Kill Baby, Kill!",
    "A Bay of Blood",
    "Rabid Dogs",
    "Monsters, Inc.",
    "    Brave(2012) ",
    "Inside Out",
    "Up(2009)",
    "The Incredibles",
    "Toy Story",
    "Toy Story 2",
    "Toy Story 3",
    "Toy Story 4",
    "Ratatouille",
    "Finding Nemo",
    "Finding Dory",
    "Wall - E",
    "Bug's Life",
    "The Seventh Seal",
    "The Virgin Spring",
    "Winchester 73(1950)",
    "The Naked Spur",
    "Warlock(1959)",
    "High Noon",
    "Johnny Guitar",
    "Rancho Notorious",
    "Forty Guns",
    "Duel in the Sun",
    "Witchfinder General",
    "Blood on Satan’s Claw",
    "The Wicker Man",
    "A Warning to the Curious(1972)",
    "Whistle and I’ll Come to You",
    "Lost Hearts(1973)",
    "Robin Redbreast(1970)",
    "A Photograph(1977)",
    "Penda’s Fen(1974)",
    "Red Shift(1978)",
    "The Woman in Black(1989)",
    "Quatermass and the Pit(1967)",
    "Stone Tape(1972)",
    "The Spirit of Dark and Lonely Water",
    "Apaches(1977)",
    "The Finishing Line(1977)",
    "The Shout(1978)",
    "Interrogation(1982)",
    "In Darkness(2011)",
    "Scum(1979)",
    "Made in Britain(1983)",
    "The Firm(1989)",
    "Culloden",
    "The War Game(1965)",
    "The Gladiators(1969)",
    "Punishment Park",
    "Rocco and His Brothers",
    "The Leopard(1963)",
    "The Damned",
    "Ossessione",
    "The Errand Boy",
    "The Ladies Man(1961)",
    "The Nutty Professor(1963) ",
    "The King of Comedy",
    "The Patsy",
    "Ashes and Diamonds",
    "A Generation(1955)",
    "Kanal(1957)",
    "Man of Marble",
    "Man of Iron(1981)",
    "Walesa: Man of Hope(2013)",
    "The Promised Land(1975)",
    "Fargo",
    "Raising Arizona",
    "Barton Fink",
    "Miller’s Crossing ",
    "The Big Lebowski",
    "No Country for Old Men",
    "A Serious Man",
    "Inside Llewyn Davis",
    "Intolerable Cruelty ",
    "The Ladykillers(2004)",
    "O Brother, Where Art Thou ?",
    "    Burn after Reading",
    "Hail, Caesar!",
    "The Passion of Joan of Arc",
    "Vampyr(1932)",
    "Day of Wrath",
    "The Parson’s Widow",
    "Chinatown(1974) ",
    "Blood Simple(1984)",
    "The Man Who Wasn’t There",
    "Brick(2005)",
    "Devil in a Blue Dress",
    "Shaft(1971)",
    "Kiss Kiss Bang Bang",
    "The Last Seduction",
    "Bound(1996)",
    "Blue Velvet(1986)",
    "Mulholland Dr.",
    "    Memento",
    "Sin City(2005)",
    "Wild at Heart(1990)",
    "Lost Highway",
    "Eraserhead",
    "Inland Empire(2006)",
    "Mad Max",
    "Mad Max The Road Warrior",
    "Mad Max beyond Thunderdome",
    "Mad Max: Fury Road",
    "Wake in Fright",
    "Long Weekend(1978)",
    "Razorback(1984)",
    "Patrick(1978)",
    "Road Games",
    "The Man from Hong Kong",
    "Dead End Drive -in",
    "    Mad Dog Morgan",
    "Stone(1974)",
    "Night of Fear",
    "Le Petit Soldat",
    "Alphaville(1965)",
    "Made in U.S.A(1966)",
    "Céline and Julie Go Boating",
    "Jeanne la Pucelle(1994)",
    "Le Pont du Nord",
    "Secret défense(1998)",
    "Poison(1991)",
    "I’m Not There(2007)",
    "Rushmore",
    "The Royal Tenenbaums ",
    "The Life Aquatic with Steve Zissou ",
    "The Darjeeling Limited ",
    "Fantastic Mr.Fox ",
    "Moonrise Kingdom",
    "The Grand Budapest Hotel",
    "The French Dispatch",
    "Isle of Dogs",
    "The Brides of Dracula",
    "The Devil Rides Out",
    "Quatermass 2 ",
    "The Hound of the Baskervilles(1959)",
    "Cash on Demand",
    "Yesterday’s Enemy(1959)",
    "Psycho(1960)",
    "Les Diaboliques(1955)",
    "Taste of Fear",
    "Paranoiac(1963)",
    "The Plague of the Zombies",
    "Twins of Evil",
    "Vampire Circus ",
    "Dracula Prince of Darkness(1966)",
    "Frankenstein Must Be Destroyed(1969)",
    "Dracula A.D. 1972 ",
    "The Phantom of the Opera(1962)",
    "The Old Dark House(1963)",
    "Demons of the Mind ",
    "To the Devil a Daughter",
    "O Auto da Compadecida",
    "Cidade de Deus",
    "Cabra Marcado Para Morrer",
    "Jogo de Cena(2007)",
    "O Pagador de Promessas(1962)",
    "Eles Não Usam Black - Tie(1981)",
    "O Caso dos Irmãos Naves(1967)",
    "São Paulo, Sociedade Anônima(1965)",
    "Serras da desordem(2006)",
    "Tropa de Elite",
    "Tropa de Elite 2: O Inimigo Agora é Outro",
    "Central do Brasil",
    "Pixote: A Lei do Mais Fraco ",
    "O Assalto ao Trem Pagador",
    "SuperOutro(1989)",
    "Que Horas Ela Volta ?",
    "    Estômago(2007)",
    "São Bernardo(1972)",
    "Rio, Zona Norte(1957)",
    "Lavoura Arcaica(2001)",
    "Os Fuzis(1964)",
    "A Hora e Vez de Augusto Matraga",
    "O Grande Momento(1958)",
    "Carandiru(2003)",
    "Abril Despedaçado(2001)",
    "Todas as Mulheres do Mundo(1966)",
    "O Lobo Atrás da Porta(2013)",
    "Terra Estrangeira(1995)",
    "Rio, 40 Graus(1955)",
    "Noite Vazia(1964)",
    "A Falecida(1968)",
    "Deus e o Diabo na Terra do Sol ",
    "O Ano em Que Meus Pais Saíram de Férias",
    "Terra em Transe(1967)",
    "Bye Bye Brasil(1980)",
    "Cinema Aspirinas e Urubus",
    "Lúcio Flávio, o Passageiro da Agonia",
    "A Hora da Estrela(1985)",
    "O Bandido da Luz Vermelha(1968)",
    "O Cangaceiro(1953)",
    "Filme Demência ",
    "Pra Frente, Brasil(1982)",
    "Sargento Getúlio(1983)",
    "O Beijo da Mulher - Aranha",
    "Limite(1931)",
    "O Homem do Sputnik ",
    "Alma Corsária ",
    "Baile Perfumado(1996)",
    "O Som ao Redor(2012)",
    "A Marvada Carne(1985)",
    "O Invasor(2001)",
    "Os Inconfidentes(1972)",
    "Bang Bang(1971)",
    "A Lira do Delírio ",
    "Madame Satã ",
    "O Dragão da Maldade contra o Santo Guerreiro",
    "Esta Noite Encarnarei no Teu Cadáver",
    "Guerra Conjugal(1974)",
    "Mar de Rosas(1978)",
    "Bar Esperança(1983)",
    "À Meia Noite Levarei Sua Alma",
    "Matou a Família e Foi ao Cinema(1969)",
    "O Signo do Caos(2005)",
    "A Idade da Terra(1980)",
    "O Anjo Nasceu(1969)",
    "Tudo Bem(1978)",
    "Dois Córregos: Verdades Submersas no Tempo",
    "Amarelo Manga(2002)",
    "Meu Nome é Tonho(1969)",
    "Meteorango Kid: Herói Intergalático",
    "Musashi Miyamoto",
    "Duel at Ichijoji Temple",
    "Duel at Ganryu Island",
    "Throne of Blood",
    "The Hidden Fortress",
    "Samurai Saga",
    "The Gambling Samurai",
    "Castle of Flames",
    "Yojimbo",
    "Sanjuro",
    "Harakiri",
    "Chushingura",
    "Three Outlaw Samurai",
    "Samurai Assassin",
    "Sword of the Beast",
    "The Sword of Doom",
    "Samurai Rebellion",
    "The Saga of Tanegashima",
    "Kill!",
    "Samurai Banners",
    "Red Lion",
    "Shinsengumi",
    "Goyokin",
    "Hitokiri(Tenchu)",
    "Mission: Iron Castle",
    "The Ambitious	",
    "Incident at Blood Pass	",
    "Shogun's Samurai",
    "The Fall of Ako Castle",
    "Kagemusha",
    "The Bushido Blade",
    "Legend of the Eight Samurai",
    "Ran",
    "Zatoichi: Darkness Is His Ally",
    "Heaven and Earth",
    "Journey of Honor",
    "47 Ronin",
    "The Twilight Samurai",
    "When the Last Sword Is Drawn",
    "Zatoichi",
    "The Hidden Blade",
    "Love and Honor",
    "Castle Under Fiery Skies",
    "13 Assassins",
    "Sword of Desperation",
    "Ichimei",
    "Rurouni Kenshin",
    "Kyoto Inferno",
    "The Legend Ends",
    "Samurai's Promise",
    "Police Story 2",
    "Spider - Man: Into the Spider - Verse",
    "Redline",
    "Bacurau",
    "The Garden of Sinners",
    "Blood: The Last Vampire",
    "Lily C.A.T.",
    "    Gyo",
    "Motel Hell",
    "Maniac(1980)",
    "My Bloody Valentine(1981)",
    "The Howling(1981)",
    "The Burning(1981)",
    "An American Werewolf in London(1981)",
    "Full Moon High ",
    "Ghost Story(1981)",
    "The Thing(1982)",
    "Q(1982)",
    "Creepshow(1982)",
    "The Hunger(1983)",
    "Psycho 2",
    "Cujo(1983)",
    "Sleepaway Camp",
    "Christine(1983)",
    "Children of the Corn",
    "Firestarter(1984)",
    "Gremlins",
    "Night of the Comet",
    "The Company of Wolves",
    "Day of the Dead(1985)",
    "The Return of the Living Dead",
    "Howling II: Stirba - Werewolf Bitch",
    "Silver Bullet(1985)",
    "Re - Animator",
    "Chopping Mall(1986)",
    "The Toxic Avenger",
    "Poltergeist II: The Other Side",
    "Psycho III",
    "Maximum Overdrive",
    "Night of the Creeps",
    "From Beyond(1986)",
    "Dolls(1987)",
    "The Lost Boys(1987)",
    "The Monster Squad(1987)",
    "Hellraiser",
    "Near Dark ",
    "Killer Klowns from Outer Space",
    "The Blob(1988)",
    "The Lair of the White Worm",
    "Elvira, Mistress of the Dark",
    "Pumpkinhead(1988)",
    "They Live(1988)",
    "Child’s Play(1988)",
    "Hellbound: Hellraiser II",
    "The ’Burbs(1989)",
    "976 - EVIL",
    "Pet Sematary(1989)",
    "Society(1989)",
    "The Thing From Another World",
    "I Was a Teenage Werewolf",
    "Dracula(1958)",
    "Night of the Living Dead(1968)",
    "Taste the Blood of Dracula",
    "Rabid(1977)",
    "Dawn of the Dead(1978)",
    "Phantasm(1979)",
    "Alligator(1980)",
    "Altered States(1980)",
    "Beyond Evil",
    "Christmas Evil",
    "City of the Living Dead",
    "Nightmare City",
    "Humanoids from the Deep",
    "Inferno(1980)",
    "Prom Night(1980)",
    "The Children(1980)",
    "The Godsend(1980)",
    "Dead & Buried(1981)",
    "Deadly Blessing",
    "Ghostkeeper(1981)",
    "Happy Birthday to Me",
    "Hell Night(1981) ",
    "Just Before Dawn",
    "Night School",
    "Nightmare(1981)",
    "Roadgames(1981)",
    "The Hand(1981)",
    "The Pit(1981)",
    "The Prowler(1981)",
    "Wolfen(1981)",
    "Alone in the Dark(1982)",
    "The Amityville Horror(1979)",
    "Amityville II: The Possession",
    "Pieces(1982)",
    "The Incubus(1982)",
    "The New York Ripper(1982)",
    "The Slumber Party Massacre(1982)",
    "Curtains(1983)",
    "Eyes of Fire(1983)",
    "House of the Long Shadows",
    "Madhouse(1974)",
    "Nightmares(1983)",
    "The Deadly Spawn ",
    "The Devonsville Terror",
    "Xtro 1982",
    "Body Double(1984)",
    "Razorback(1984)",
    "The Initiation(1984)",
    "Phenomena",
    "The Bad Seed",
    "The New Kids(1985)",
    "Warning Sign(1985)",
    "Demons 2",
    "Gothic(1986)",
    "House(1985)",
    "The Abomination(1986)",
    "The Hitcher(1986)",
    "Vamp 1986",
    "Angel Heart",
    "Creepshow 2",
    "Jaws",
    "Opera(1987)",
    "Prince of Darkness",
    "The Hidden(1987)",
    "The Stepfather(1987)",
    "American Gothic",
    "Brain Damage",
    "Night of the Demons",
    "Pin(1988)",
    "Slugs(1988)",
    "The Serpent and the Rainbow",
    "Dr.Caligari(1989)",
    "I, Madman(1989)",
    "Intruder(1989)",
    "Parents(1989)",
    "Vampire’s Kiss",
    "I Know What You Did Last Summer",
    "Final Destination",
    "Final Destination 2",
    "Final Destination 3",
    "Final Destination 5",
    "Hostel(2005)",
    "Insidious(2010)",
    "The Cabin in the Woods",
    "It Follows",
    "The Shape of Water",
    "Pan’s Labyrinth",
    "The Devil’s Backbone",
    "Cronos(1993)",
    "Blade",
    "Blade II",
    "Hellboy",
    "Hellboy II: The Golden Army ",
    "Pacific Rim(2013)",
    "Nightmare Alley",
    "Mimic(1997)",
    "Crimson Peak",
    "The Godfather ",
    "The Godfather Part II",
    "The Godfather Part III",
    "Apocalypse Now",
    "The Conversation",
    "Bram Stoker’s Dracula(1992)",
    "Dementia 13(1963)",
    "Mind Game(2004)",
    "Midnight Cowboy",
    "Marathon Man(1976)",
    "Frailty(2001)",
    "Saint Maud",
    "The House of the Devil",
    "Prince of Darkness(1987)",
    "The Sacrament(2013)",
    "Darkman(1990)",
    "Drag Me to Hell",
    "The Quick and the Dead",
    "A Simple Plan",
    "The Gift(2000)",
    "Get Carter(1971)",
    "Croupier(1998)",
    "I’ll Sleep When I’m Dead(2003)",
    "Pulp(1972)",
    "The Long Goodbye’s(1973)",
    "Black Rainbow(1989)",
    "In the Cut(2003)",
    "The Story of Lover’s Rock(2011)",
    "Real Life(1979)",
    "Defending Your Life(1991)",
    "Modern Romance(1981)",
    "Lost in America(1985)",
    "Mother(1996)",
    "Running Out of Time(1999)",
    "PTU(2003)",
    "Exiled(2006)",
    "Throw Down(2004)",
    "The Tracker(2002)",
    "Ten Canoes(2006)",
    "Charlie’s Country(2013)",
    "Storm Boy(1976)",
    "Mad Dog Morgan(1976)",
    "The Last Wave(1977)",
    "Rabbit Proof - Fence(2002)",
    "The Proposition(2005)",
    "The Chant of Jimmie Blacksmith(1978)",
    "Mystery Road(2013)",
    "Goldstone(2016)",
    "Chocolat(1988)",
    "White Material(2009)",
    "I Can't Sleep (1994)",
    "Trouble Every Day(2001)",
    "Bastards(2013)",
    "High Life(2018)",
];